---
project_name: PROJECTNAME
output_dir: /cluster/projects/pughlab/projects/PROJECTNAME/ShallowWGS
seq_type: wgs # must be one of exome, targeted, rna or wgs
seq_center: PMGC
platform: Illumina
flowcell_type: patterned # one of random or patterned, depends on the instrument used: https://knowledge.illumina.com/instrumentation/general/instrumentation-general-faq-list/000007786
hpc_group:
# reference files
ref_type: hg38 # one of hg38, hg19, GRCh37 or GRCh38 (minimal testing with GRCh37/8)
reference: /cluster/tools/data/genomes/human/hg38/iGenomes/Sequence/WholeGenomeFasta/genome.fa
gnomad: /cluster/projects/pughlab/references/ExAC/af-only-gnomad.hg38.vcf.gz 
# tool versions
perl_version: 5.40.0
fastp_version: 0.23.1
fastqc_version: 0.11.5
bwa_version: 0.7.15
samtools_version: 1.20
picard_version: 2.10.9
sambamba_version: 0.7.0 
bedtools_version: 2.27.1
gatk_version: 3.8
gatk_cnv_version: 4.6.0.0
ichor_cna_version: 0.3.2
r_version: 4.1.0
# tool specific parameters
trim_adapters:
    run: Y
    parameters:
        trim:
            mem: 4G
            time: '24:00:00'
fastqc:
    run: Y
    parameters:
        fastqc:
            mem: 2G
            time: '24:00:00'
bwa:
    run: Y
    aligner: bwamem
    reference: /cluster/projects/pughlab/references/bwa_index/hg38/genome.fa
    parameters:
        bwa:
            mem:
                normal: 8G
                tumour: 8G
            n_cpus:
                normal: 4
                tumour: 4
            time:
                normal: '24:00:00'
                tumour: '48:00:00'
        sort:
            mem:
                normal: 4G
                tumour: 4G
            time:
                normal: '24:00:00'
                tumour: '48:00:00'
        index:
            mem:
                normal: 2G
                tumour: 2G
            time:
                normal: '05:00:00'
                tumour: '05:00:00'
        merge:
            tool: 'picard' # or sambamba
            mark_dup: Y
            n_cpus: 1 # or more for sambamba
            java_mem:
                normal: 7g
                tumour: 11g
            mem:
                normal: 8G
                tumour: 12G
            time:
                normal: '48:00:00'
                tumour: '48:00:00'
gatk:
    run: N
bamqc:
    run: Y
    parameters:
        contest:
            run: N
        qc:
            java_mem: 3g
            mem: 4G
            time: '48:00:00'
        coverage:
            java_mem: 3g
            mem: 4G
            time: '48:00:00'
            n_cpus: 1
        callable_bases:
            min_depth:
                tumour: 20
                normal: 15
            mem: 4G
            time: '48:00:00'
ichor_cna:
    run: Y
    pon: #/cluster/projects/pughlab/references/panel_of_normals/hg38/IchorCNA/pon_ichorCNA__CHARM__median.rds
    parameters:
        downsample:
            run: N
            n_reads: 50000000 # takes priority over scale factor
            scale_factor: 0.01 # scale factor = probability of selecting a read
            mem: 2G
            time: '48:00:00'
        readcounter:
            mem: 2G
            time: '24:00:00'
        create_pon:
            run: N
            mem: 2G
            time: '24:00:00'
        ichor_cna:
            mem: 2G
            time: '24:00:00'
haplotype_caller:
    run: N
mutect:
    run: N
mutect2:
    run: N
manta:
    run: N
strelka:
    run: N
varscan:
    run: N
somaticsniper:
    run: N
vardict:
    run: N
pindel:
    run: N
gatk_cnv:
    run: N
delly:
    run: N
novobreak:
    run: N
svict:
    run: N
panelcn_mops:
    run: N
ascat:
    run: N
msi_sensor:
    run: N
mavis:
    run: N
summarize_steps:
    lib_path: '/cluster/projects/pughlab/src/r_lib/library/4.1/'
    run_cosmic_sbs: # note that signatures (path) takes priority over cosmic_version
        run: N
        signatures: #/cluster/projects/pughlab/references/COSMIC/Mutational_Sigatures/COSMIC_v3.2_SBS_GRCh38.txt
        cosmic_version: 3.3 # one of 3.0, 3.1, 3.2, 3.3
    run_mutsig: N # only recommended if you many samples
    run_chord: N
    run_hrdetect: N
