---
project_name: PROJECTNAME
output_dir: /cluster/projects/pughlab/projects/PROJECTNAME
sample_type: # optional; can be germline or ctdna
seq_type: emseq # must be one of exome, targeted, rna, wgs or emseq
seq_center: PMGC
platform: Illumina
flowcell_type: patterned # see here for details: https://knowledge.illumina.com/instrumentation/general/instrumentation-general-faq-list/000007786
hpc_group: 
# reference files
ref_type: hg38 # one of hg38, hg19, GRCh37 or GRCh38 (minimal testing with GRCh37/8)
reference: /cluster/tools/data/genomes/human/hg38/iGenomes/Sequence/WholeGenomeFasta/genome.fa
baits_bed: /cluster/projects/pughlab/references/intervals/MultiMMR_panel/version2/MTE/bait_probes_merged_sorted.bed
targets_bed: /cluster/projects/pughlab/references/intervals/MultiMMR_panel/version2/MTE/target_covered_by_probes_sorted.bed
gnomad: /cluster/projects/pughlab/references/ExAC/af-only-gnomad.hg38.vcf.gz 
# tool versions
perl_version: 5.40.0
trim_galore_version: 0.6.6
fastqc_version: 0.11.5
bwa_meth_version: 0.2.7 # for use with module load bwa_meth/version (if available)
bwa_meth_path: #/cluster/projects/pughlab/bin/bwa_meth/v0.2.7/bwameth.py
mark_nonconverted_path: /cluster/projects/pughlab/bin/mark-nonconverted-reads/mark-nonconverted-reads.py
bwa_version: 0.7.15
samtools_version: 1.20
methyldackel_version: 0.6.1
python3_version: 3.10.9
picard_version: 2.10.9
sambamba_version: 0.7.0 
gatk_cnv_version: 4.6.0.0 # for qc tools
r_version: 4.1.0
# tool specific parameters
trim_adapters:
    run: Y
    parameters:
        trim:
            mem: 2G
            time: '04:00:00'
fastqc:
    run: Y
    parameters:
        fastqc:
            mem: 2G
            time: '02:00:00'
bwa:
    run: Y
    aligner: bwameth
    reference: /cluster/projects/pughlab/references/bwameth_index/hg38/genome.fa
    parameters:
        bwa:
            n_cpus:
                normal: 8
                tumour: 8
            mem:
                normal: 16G
                tumour: 16G
            time:
                normal: '04:00:00'
                tumour: '04:00:00'
        sort:
            mem:
                normal: 4G
                tumour: 4G
            time:
                normal: '04:00:00'
                tumour: '04:00:00'
        index:
            mem:
                normal: 1G
                tumour: 1G
            time:
                normal: '02:00:00'
                tumour: '02:00:00'
        filter:
            mem: 2G
            time: '04:00:00'
        merge:
            tool: 'sambamba'
            mark_dup: Y
            n_cpus: 1
            java_mem:
                normal: 7g
                tumour: 7g
            mem:
                normal: 8G
                tumour: 8G
            time:
                normal: '04:00:00'
                tumour: '04:00:00'
bamqc:
    run: Y
    parameters:
        qc:
            java_mem: 3g
            mem: 4G
            time: '04:00:00'
methyldackel:
    run: Y
    parameters:
        mbias:
            mem: 2G
            time: '04:00:00'
        extract:
            non_cpg: Y # should CHG and CHH metrics be collected?
            mem: 2G
            time: '04:00:00'
            n_cpus: 1
